// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_array.proto

#ifndef PROTOBUF_event_5farray_2eproto__INCLUDED
#define PROTOBUF_event_5farray_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace event_array {
namespace protobuf {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_event_5farray_2eproto();
void protobuf_AssignDesc_event_5farray_2eproto();
void protobuf_ShutdownFile_event_5farray_2eproto();

class Event_Array;
class Event_Array_Event;

// ===================================================================

class Event_Array_Event : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:event_array.protobuf.Event_Array.Event) */ {
 public:
  Event_Array_Event();
  virtual ~Event_Array_Event();

  Event_Array_Event(const Event_Array_Event& from);

  inline Event_Array_Event& operator=(const Event_Array_Event& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Event_Array_Event& default_instance();

  void Swap(Event_Array_Event* other);

  // implements Message ----------------------------------------------

  inline Event_Array_Event* New() const { return New(NULL); }

  Event_Array_Event* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Event_Array_Event& from);
  void MergeFrom(const Event_Array_Event& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Event_Array_Event* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  double timestamp() const;
  void set_timestamp(double value);

  // optional int32 x = 2;
  void clear_x();
  static const int kXFieldNumber = 2;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // optional int32 y = 3;
  void clear_y();
  static const int kYFieldNumber = 3;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // optional int32 polarity = 4;
  void clear_polarity();
  static const int kPolarityFieldNumber = 4;
  ::google::protobuf::int32 polarity() const;
  void set_polarity(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:event_array.protobuf.Event_Array.Event)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double timestamp_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  ::google::protobuf::int32 polarity_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_event_5farray_2eproto();
  friend void protobuf_AssignDesc_event_5farray_2eproto();
  friend void protobuf_ShutdownFile_event_5farray_2eproto();

  void InitAsDefaultInstance();
  static Event_Array_Event* default_instance_;
};
// -------------------------------------------------------------------

class Event_Array : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:event_array.protobuf.Event_Array) */ {
 public:
  Event_Array();
  virtual ~Event_Array();

  Event_Array(const Event_Array& from);

  inline Event_Array& operator=(const Event_Array& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Event_Array& default_instance();

  void Swap(Event_Array* other);

  // implements Message ----------------------------------------------

  inline Event_Array* New() const { return New(NULL); }

  Event_Array* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Event_Array& from);
  void MergeFrom(const Event_Array& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Event_Array* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Event_Array_Event Event;

  // accessors -------------------------------------------------------

  // repeated .event_array.protobuf.Event_Array.Event event = 1;
  int event_size() const;
  void clear_event();
  static const int kEventFieldNumber = 1;
  const ::event_array::protobuf::Event_Array_Event& event(int index) const;
  ::event_array::protobuf::Event_Array_Event* mutable_event(int index);
  ::event_array::protobuf::Event_Array_Event* add_event();
  ::google::protobuf::RepeatedPtrField< ::event_array::protobuf::Event_Array_Event >*
      mutable_event();
  const ::google::protobuf::RepeatedPtrField< ::event_array::protobuf::Event_Array_Event >&
      event() const;

  // @@protoc_insertion_point(class_scope:event_array.protobuf.Event_Array)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::event_array::protobuf::Event_Array_Event > event_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_event_5farray_2eproto();
  friend void protobuf_AssignDesc_event_5farray_2eproto();
  friend void protobuf_ShutdownFile_event_5farray_2eproto();

  void InitAsDefaultInstance();
  static Event_Array* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Event_Array_Event

// optional double timestamp = 1;
inline void Event_Array_Event::clear_timestamp() {
  timestamp_ = 0;
}
inline double Event_Array_Event::timestamp() const {
  // @@protoc_insertion_point(field_get:event_array.protobuf.Event_Array.Event.timestamp)
  return timestamp_;
}
inline void Event_Array_Event::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:event_array.protobuf.Event_Array.Event.timestamp)
}

// optional int32 x = 2;
inline void Event_Array_Event::clear_x() {
  x_ = 0;
}
inline ::google::protobuf::int32 Event_Array_Event::x() const {
  // @@protoc_insertion_point(field_get:event_array.protobuf.Event_Array.Event.x)
  return x_;
}
inline void Event_Array_Event::set_x(::google::protobuf::int32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:event_array.protobuf.Event_Array.Event.x)
}

// optional int32 y = 3;
inline void Event_Array_Event::clear_y() {
  y_ = 0;
}
inline ::google::protobuf::int32 Event_Array_Event::y() const {
  // @@protoc_insertion_point(field_get:event_array.protobuf.Event_Array.Event.y)
  return y_;
}
inline void Event_Array_Event::set_y(::google::protobuf::int32 value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:event_array.protobuf.Event_Array.Event.y)
}

// optional int32 polarity = 4;
inline void Event_Array_Event::clear_polarity() {
  polarity_ = 0;
}
inline ::google::protobuf::int32 Event_Array_Event::polarity() const {
  // @@protoc_insertion_point(field_get:event_array.protobuf.Event_Array.Event.polarity)
  return polarity_;
}
inline void Event_Array_Event::set_polarity(::google::protobuf::int32 value) {
  
  polarity_ = value;
  // @@protoc_insertion_point(field_set:event_array.protobuf.Event_Array.Event.polarity)
}

// -------------------------------------------------------------------

// Event_Array

// repeated .event_array.protobuf.Event_Array.Event event = 1;
inline int Event_Array::event_size() const {
  return event_.size();
}
inline void Event_Array::clear_event() {
  event_.Clear();
}
inline const ::event_array::protobuf::Event_Array_Event& Event_Array::event(int index) const {
  // @@protoc_insertion_point(field_get:event_array.protobuf.Event_Array.event)
  return event_.Get(index);
}
inline ::event_array::protobuf::Event_Array_Event* Event_Array::mutable_event(int index) {
  // @@protoc_insertion_point(field_mutable:event_array.protobuf.Event_Array.event)
  return event_.Mutable(index);
}
inline ::event_array::protobuf::Event_Array_Event* Event_Array::add_event() {
  // @@protoc_insertion_point(field_add:event_array.protobuf.Event_Array.event)
  return event_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::event_array::protobuf::Event_Array_Event >*
Event_Array::mutable_event() {
  // @@protoc_insertion_point(field_mutable_list:event_array.protobuf.Event_Array.event)
  return &event_;
}
inline const ::google::protobuf::RepeatedPtrField< ::event_array::protobuf::Event_Array_Event >&
Event_Array::event() const {
  // @@protoc_insertion_point(field_list:event_array.protobuf.Event_Array.event)
  return event_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace event_array

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_event_5farray_2eproto__INCLUDED
